Add edge-ami workflow jobs in RHEL-9.3 and CS9
virt-s1/rhel-edge pull request #3741
Opened 2023-07-25 10:26 UTC by mcattamoredhat

This PR includes workflow jobs to trigger edge-ami CI tests in RHEL-9.3 and CS9.

2023-07-25 10:31 UTC, mcattamoredhat commented
/test-cs9

2023-07-25 10:40 UTC, mcattamoredhat commented
/test-rhel-9-3

2023-07-25 14:05 UTC, henrywang requested changes

2023-07-25 14:05 UTC, henrywang commented on .github/workflows/rhel-9-3.yml
> +    runs-on: [kite, x86_64, rhos-01, rhel-9-3, large]
Let's use medium one in this case.

2023-07-26 09:50 UTC, mcattamoredhat commented
/test-rhel-9-3

2023-07-26 09:50 UTC, mcattamoredhat commented on .github/workflows/rhel-9-3.yml
> +    runs-on: [kite, x86_64, rhos-01, rhel-9-3, large]
Done!

2023-07-26 11:23 UTC, mcattamoredhat commented
/test-cs9

2023-07-26 13:05 UTC, mcattamoredhat commented
/test-rhel-8-9

2023-07-26 13:05 UTC, mcattamoredhat commented
/test-rhel-9-2

2023-07-26 16:17 UTC, mcattamoredhat commented
Failure in edge-simplified-installer-9.3 and edge-simplified-installer-cs9 is due to known FDO bug.

2023-07-26 16:18 UTC, mcattamoredhat commented
/test-cs8

2023-07-26 16:19 UTC, mcattamoredhat commented
/test-f38

2023-07-27 08:34 UTC, mcattamoredhat commented
/test-rhel-8-8

2023-08-07 13:55 UTC, mcattamoredhat commented
/test-rhel-9-3-simplified

2023-08-07 13:55 UTC, mcattamoredhat commented
/test-cs9-simplified

2023-08-07 13:58 UTC, henrywang approved these changes
LGTM. Thanks.

2023-08-07 13:58 UTC, merged