test: add test case iot-qcow2-image
virt-s1/rhel-edge pull request #4982
Opened 2023-10-10 03:07 UTC by yih-redhat

2023-10-10 13:49 UTC, henrywang requested changes

2023-10-11 07:31 UTC, yih-redhat commented on ostree-iot-qcow2.sh
> +# Compare rpm package version
fixed

2023-10-11 07:31 UTC, yih-redhat commented on ostree-iot-qcow2.sh
> +        sudo composer-cli --json compose start-ostree --ref "$OSTREE_REF" --parent "$parent_ref" --url "$repo_url" "$blueprint_name" "$image_type" | tee "$COMPOSE_START"
fixed

2023-10-11 07:31 UTC, yih-redhat commented on ostree-iot-qcow2.sh
> +## Build edge-raw-image
fixed

2023-10-11 07:32 UTC, yih-redhat commented
all comments resolved and test passed, ready for merge now.

2023-10-11 16:21 UTC, henrywang commented
Thanks @yih-redhat. I merged PR #4990. Could you please make a rebase and use `/test-f38-qcow2` to trigger test.

2023-10-12 03:20 UTC, yih-redhat commented
/test-f38-qcow2

2023-10-12 05:27 UTC, yih-redhat commented
/test-f38-qcow2

2023-10-12 06:54 UTC, henrywang approved these changes

2023-10-12 06:54 UTC, merged